spring:
  application:
    name: UniAttendanceSystem

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  defer-datasource-initialization: true

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cs544_attendance?createDatabaseIfNotExist=true
    hikari:
      maximum-pool-size: 10


  sql:
    init:
      mode: ALWAYS


  data:
    jdbc:
      dialect: mysql


